// TODO: Replace with Supabase query via useListings hook

import type { Listing } from "./types";

export const MOCK_LISTINGS: Listing[] = [
  {
    id: "mock-001",
    name: "Beachfront Villa, Mactan Island",
    price: "₱18,500,000",
    priceShort: "₱18.5M",
    type: "house",
    badge: "For Sale",
    badgeClass: "bg-primary text-white",
    beds: 4,
    baths: 3,
    area: 280,
    lot: 450,
    location: "Punta Engano, Lapu-Lapu City",
    img: "from-cyan-800 via-teal-700 to-cyan-600",
    agent: {
      name: "Maria Reyes",
      initials: "MR",
      company: "Cebu Grand Realty",
      experience: 12,
    },
    description:
      "Stunning beachfront villa with direct ocean access and private pool. Wake up to panoramic views of the Cebu Strait. Open-plan living, high ceilings, fully furnished — perfect for families or as a premium rental investment.",
    features: [
      "Private pool",
      "Direct ocean access",
      "Fully furnished",
      "High ceilings",
      "Covered parking",
    ],
    mapPos: { top: "50%", left: "82%" },
    tags: ["Beachfront", "Luxury", "Investment"],
  },
  {
    id: "mock-002",
    name: "Modern Tropical House, Cordova",
    price: "₱8,500,000",
    priceShort: "₱8.5M",
    type: "house",
    badge: "New",
    badgeClass: "bg-green text-white",
    beds: 3,
    baths: 2,
    area: 150,
    lot: 200,
    location: "Pilipog, Cordova",
    img: "from-emerald-700 via-green-600 to-teal-600",
    agent: {
      name: "Maria Reyes",
      initials: "MR",
      company: "Cebu Grand Realty",
      experience: 12,
    },
    description:
      "Brand new 3-bedroom modern tropical home in the heart of Cordova. Open-concept design, natural ventilation, native wood accents, spacious lanai. Walking distance to local markets and the beach.",
    features: [
      "Open-concept layout",
      "Native wood accents",
      "Spacious lanai",
      "Natural ventilation",
      "Near beach",
    ],
    mapPos: { top: "58%", left: "72%" },
    tags: ["Modern", "Tropical", "New build"],
  },
  {
    id: "mock-003",
    name: "2BR Condo, Cebu IT Park",
    price: "₱4,200,000",
    priceShort: "₱4.2M",
    type: "condo",
    badge: "For Sale",
    badgeClass: "bg-primary text-white",
    beds: 2,
    baths: 1,
    area: 42,
    lot: null,
    location: "Apas, Cebu City",
    img: "from-violet-700 via-purple-600 to-indigo-600",
    agent: {
      name: "Maria Reyes",
      initials: "MR",
      company: "Cebu Grand Realty",
      experience: 12,
    },
    description:
      "Sleek 2-bedroom condo in the vibrant IT Park district. Walking distance to restaurants, cafes, and tech offices. High floor with city views, gym, pool, 24/7 security. Ideal for professionals or investors.",
    features: [
      "City views",
      "Gym & pool access",
      "24/7 security",
      "Walking to IT Park",
      "Pet-friendly",
    ],
    mapPos: { top: "28%", left: "58%" },
    tags: ["City living", "Investment", "IT Park"],
  },
  {
    id: "mock-004",
    name: "Corner Lot, Mandaue City",
    price: "₱3,800,000",
    priceShort: "₱3.8M",
    type: "lot",
    badge: "For Sale",
    badgeClass: "bg-primary text-white",
    beds: null,
    baths: null,
    area: null,
    lot: 200,
    location: "Bakilid, Mandaue City",
    img: "from-amber-700 via-yellow-600 to-orange-500",
    agent: {
      name: "Maria Reyes",
      initials: "MR",
      company: "Cebu Grand Realty",
      experience: 12,
    },
    description:
      "Prime corner lot in a fast-developing residential area of Mandaue City. Flat terrain, ready for construction. Close to major roads, malls, and schools. Clean title, all utilities available.",
    features: [
      "Corner lot",
      "Clean title",
      "Flat terrain",
      "All utilities available",
      "Near major roads",
    ],
    mapPos: { top: "22%", left: "63%" },
    tags: ["Prime location", "Development", "Corner lot"],
  },
  {
    id: "mock-005",
    name: "Furnished Condo, Ayala Center",
    price: "₱25,000/mo",
    priceShort: "₱25K/mo",
    type: "condo",
    badge: "For Rent",
    badgeClass: "bg-ocean text-white",
    beds: 2,
    baths: 1,
    area: 55,
    lot: null,
    location: "Cebu IT Park, Cebu City",
    img: "from-sky-700 via-blue-600 to-cyan-600",
    agent: {
      name: "Maria Reyes",
      initials: "MR",
      company: "Cebu Grand Realty",
      experience: 12,
    },
    description:
      "Fully furnished 2-bedroom condo near Ayala Center Cebu. Move-in ready with modern appliances, fast WiFi, and access to premium amenities. Perfect for expats and professionals.",
    features: [
      "Fully furnished",
      "Fast WiFi",
      "Air conditioning",
      "Washing machine",
      "Near Ayala mall",
    ],
    mapPos: { top: "34%", left: "56%" },
    tags: ["Furnished", "Expat-friendly", "Short-term ok"],
  },
  {
    id: "mock-006",
    name: "3BR Townhouse, Talisay City",
    price: "₱6,200,000",
    priceShort: "₱6.2M",
    type: "townhouse",
    badge: "For Sale",
    badgeClass: "bg-primary text-white",
    beds: 3,
    baths: 2,
    area: 110,
    lot: 80,
    location: "San Isidro, Talisay City",
    img: "from-rose-700 via-red-600 to-orange-600",
    agent: {
      name: "Maria Reyes",
      initials: "MR",
      company: "Cebu Grand Realty",
      experience: 12,
    },
    description:
      "Newly built 3-bedroom townhouse in a quiet and secure subdivision in Talisay City. Modern design, covered parking, private backyard. Minutes from the South Road Properties expressway.",
    features: [
      "Modern design",
      "Covered parking",
      "Private backyard",
      "Near SRP expressway",
      "Secure subdivision",
    ],
    mapPos: { top: "64%", left: "38%" },
    tags: ["Family home", "Subdivision", "New build"],
  },
];
